FROM ghcr.io/astral-sh/uv:latest as builder

WORKDIR /app
COPY . .
RUN uv sync

FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /app /app
RUN pip install uv

EXPOSE 8000
CMD ["uv", "run", "fastapi", "run", "server.py"]
